stages:
  - install_dependencies
  - test
  - deploy

image: node:16

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - node_modules/

install_dependencies:
  stage: install_dependencies
  except:
    - tags
  script:
    - npm install --legacy-peer-deps

test:
  stage: test
  except:
    - tags
  script:
    - npm test -- --coverage
  coverage: /All\sfiles.*?\s+(\d+.\d+)/
